CREATE TABLE airport
(
    id          INTEGER      NOT NULL AUTO_INCREMENT,
    AIRPORT_CODE VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE airline
(
    id          INTEGER      NOT NULL AUTO_INCREMENT,
    AIRLINE_CODE VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE flight
(
    id           VARCHAR(128)      NOT NULL,
    FLIGHT_NUMBER VARCHAR(128) NOT NULL,
    FLIGHT_DATE date NOT NULL,
    AIRLINE_ID           INTEGER      NOT NULL ,
    SOURCE_AIRPORT_ID           INTEGER      NOT NULL ,
    DEST_AIRPORT_ID           INTEGER      NOT NULL ,

    PRIMARY KEY (id)
);

ALTER TABLE flight ADD FOREIGN KEY ( AIRLINE_ID ) REFERENCES airline( id ) ;
ALTER TABLE flight ADD FOREIGN KEY ( SOURCE_AIRPORT_ID ) REFERENCES airport( id ) ;
ALTER TABLE flight ADD FOREIGN KEY ( DEST_AIRPORT_ID ) REFERENCES airport( id ) ;
